#############################################################################
# Makefile for building: Reversi
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Apr 11 14:27:38 2012
# Project:  Reversi.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Reversi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQt3Support -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Point.cpp \
		src/Lines.cpp \
		src/ClickableLabel.cpp \
		main.cpp \
		reversi.cpp moc_ClickableLabel.cpp \
		moc_reversi.cpp
OBJECTS       = Point.o \
		Lines.o \
		ClickableLabel.o \
		main.o \
		reversi.o \
		moc_ClickableLabel.o \
		moc_reversi.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Reversi.pro
QMAKE_TARGET  = Reversi
DESTDIR       = 
TARGET        = Reversi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_reversi.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Reversi.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQt3Support.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Reversi.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQt3Support.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Reversi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Reversi1.0.0 || $(MKDIR) .tmp/Reversi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Reversi1.0.0/ && $(COPY_FILE) --parents src/Point.h src/Lines.h src/ClickableLabel.h reversi.h .tmp/Reversi1.0.0/ && $(COPY_FILE) --parents src/Point.cpp src/Lines.cpp src/ClickableLabel.cpp main.cpp reversi.cpp .tmp/Reversi1.0.0/ && $(COPY_FILE) --parents reversi.ui .tmp/Reversi1.0.0/ && (cd `dirname .tmp/Reversi1.0.0` && $(TAR) Reversi1.0.0.tar Reversi1.0.0 && $(COMPRESS) Reversi1.0.0.tar) && $(MOVE) `dirname .tmp/Reversi1.0.0`/Reversi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Reversi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ClickableLabel.cpp moc_reversi.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ClickableLabel.cpp moc_reversi.cpp
moc_ClickableLabel.cpp: src/ClickableLabel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ClickableLabel.h -o moc_ClickableLabel.cpp

moc_reversi.cpp: ui_reversi.h \
		src/ClickableLabel.h \
		src/Lines.h \
		src/Point.h \
		reversi.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) reversi.h -o moc_reversi.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_reversi.h
compiler_uic_clean:
	-$(DEL_FILE) ui_reversi.h
ui_reversi.h: reversi.ui
	/usr/bin/uic-qt4 reversi.ui -o ui_reversi.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Point.o: src/Point.cpp src/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o src/Point.cpp

Lines.o: src/Lines.cpp src/Lines.h \
		src/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Lines.o src/Lines.cpp

ClickableLabel.o: src/ClickableLabel.cpp src/ClickableLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClickableLabel.o src/ClickableLabel.cpp

main.o: main.cpp reversi.h \
		ui_reversi.h \
		src/ClickableLabel.h \
		src/Lines.h \
		src/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

reversi.o: reversi.cpp reversi.h \
		ui_reversi.h \
		src/ClickableLabel.h \
		src/Lines.h \
		src/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reversi.o reversi.cpp

moc_ClickableLabel.o: moc_ClickableLabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClickableLabel.o moc_ClickableLabel.cpp

moc_reversi.o: moc_reversi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reversi.o moc_reversi.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

